# Generated by Django 4.1.6 on 2023-02-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('address', models.CharField(max_length=80)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='AdsModel',
        ),
    ]
