# Generated by Django 4.1.6 on 2023-02-09 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ads', '0003_alter_ads_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
