# Generated by Django 4.1.6 on 2023-02-25 17:33

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0006_alter_ads_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=django.db.models.fields.IntegerField)),
                ('name', models.CharField(max_length=30, null=True)),
                ('items', models.ManyToManyField(to='ads.ads')),
            ],
        ),
    ]
